version: '3.2'
services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - ./prometheus:/etc/prometheus/
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - 0.0.0.0:9090:9090
        restart: always
    
    alertmanager-bot:
        image: metalmatze/alertmanager-bot:0.4.3
        container_name: alertmanager-bot
        volumes:
            - ./data:/data
        command:
            - --alertmanager.url=http://alertmanager:9093
            - --log.level=info
            - --store=bolt
            - --bolt.path=/data/bot.db
        environment:
            TELEGRAM_ADMIN: "80446319"
            TELEGRAM_TOKEN: 5315478389:AAF7Va3Da7QWKAcPemtFkrdNI3wLw2Hpe_Y
        ports:
            - 127.0.0.1:8080:8080
        restart: always

    alertmanager:
        image: prom/alertmanager:v0.24.0
        container_name: alertmanager
        ports:
           - 127.0.0.1:9093:9093
        volumes:
           - ./alertmanager/:/etc/alertmanager/
        restart: always
        command:
           - '--config.file=/etc/alertmanager/config.yml'
           - '--storage.path=/etc/alertmanager/data'

     
    node-exporter:
        image: prom/node-exporter
        container_name: node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        hostname: monitoring
        command:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
            - 0.0.0.0:9100:9100
        restart: always

    blackbox-exporter:
        image: prom/blackbox-exporter
        container_name: blackbox-exporter
        ports:
          - 0.0.0.0:9115:9115
        restart: always
        volumes: 
          - ./blackbox:/config
        command: --config.file=/config/blackbox.yml

    grafana:
        image: grafana/grafana
        container_name: grafana
        depends_on:
            - prometheus
        ports:
            - 0.0.0.0:3000:3000
        volumes:
            - ./grafana:/var/lib/grafana
            - ./grafana/provisioning/:/etc/grafana/provisioning/
            - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        restart: always
