---
# tasks file for docker

- name: Install apt-transport-https
  when: ansible_os_family == "Debian"
  apt:
    name: "apt-transport-https"
    state: present
    update_cache: yes

- name: Add Docker APT GPG key
  when: ansible_os_family == "Debian"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: "docker"
    
- name: Add Docker yum repository
  when: ansible_os_family == "RedHat"
  yum_repository:
    name: Docker
    description: Docker Repository
    file: docker
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install docker (RHEL/CentOS)
  when: ansible_os_family == "RedHat"
  yum:
    name:
      - docker-ce 
      - docker-ce-cli 
      - docker-compose
    state: present
    
- name: Install docker (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    package:
      - docker-ce 
      - docker-ce-cli 
      - docker-compose
    update_cache: yes
    state: present

      

- name: Prevent Docker from being upgraded
  when: ansible_os_family == "Debian"
  dpkg_selections:
    name: docker-ce
    selection: hold

- name: Add ubuntu user to docker group
  user:
      name: ubuntu
      group: docker 

- name: Restart docker
  service:
      name: docker
      enabled: yes
      daemon_reload: yes
      state: restarted       